name: 'docker-auto-import'
description: 'A auto import docker image into server without registry server'
inputs:
  image:
    description: 'Image name for build'
    required: false
  version:
    description: 'Image version (Tag) for build'
    required: false
    default: 'latest'
  dockerfile:
    description: 'Docker image file (Default: ./Dockerfile)'
    required: false
    default: './Dockerfile'
  url:
    description: "URL docker tcp server"
    required: true
  
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'